RADAR_PORT_LOWER=$(shell echo $(RADAR_PORT) | tr A-Z a-z)
PATH_LIBSTM32=$(PAPARAZZI_SRC)/sw/ext/libstm32


$(TARGET).CFLAGS += -DUSE_$(RADAR_PORT)
$(TARGET).CFLAGS += -D$(RADAR_PORT)_BAUD=$(RADAR_BAUD)
$(TARGET).CFLAGS += -I$(PATH_LIBSTM32)

$(TARGET).CFLAGS += -DRADAR_DEVICE=$(RADAR_PORT_LOWER) -DRADAR_UART=$(RADAR_PORT_LOWER)
$(TARGET).srcs += subsystems/actuators/motor_info.c


